name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cofigurar o Github Pages
        uses: actions/configure-pages@v4

             
      - name: Compactar Artefatos do Site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

          
      - name: Publicar no Github Pages
        uses: actions/deploy-pages@v4
